const express = require('express');
const router = express.Router();
const { shiftRouter, dailyRouter, weeklyRouter } = require('./checkList.routes');
router.use('/sites', require('./sites.routes'));
router.use('/sections', require('./sections.routes'));
router.use('/dashboard', require('./dashboard.routes'));
router.use('/cleaning-logs', require('./cleaningLogs.routes'));
router.use('/planogram-checks', require('./planogramChecks.routes'));
router.use('/expiry-logs', require('./expiryLogs.routes'));
router.use('/order-items', require('./orderItems.routes'));
router.use('/checklist', shiftRouter);
router.use('/daily-checklist', dailyRouter);
router.use('/weekly-checklist', weeklyRouter);
router.use('/sandwich-tracker', require('./sandwichTracker.routes'));
router.use('/testwash', require('./testwash.routes'));
router.use('/weekly-report', require('./weeklyReport.routes'));
router.use('/section-activity', require('./sectionActivity.routes'));
router.use('/employees', require('./employees.routes'));
router.use('/easter-egg', require('./easterEgg.routes'));
module.exports = router;